# Generated by Django 4.2 on 2023-04-29 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("baseball", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guess",
            options={
                "ordering": ["count"],
                "verbose_name": "랭킹",
                "verbose_name_plural": "랭킹셋",
            },
        ),
        migrations.AlterField(
            model_name="guess",
            name="userid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
